# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfile', models.FileField(upload_to='')),
            ],
        ),
    ]
