# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='userfile',
            new_name='actualfile',
        ),
    ]
