# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0003_auto_20170628_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='actualfile',
            field=models.FileField(upload_to=''),
        ),
    ]
