# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0004_auto_20170628_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='filename',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
