# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0005_userfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
