# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0006_auto_20170629_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='filename',
            new_name='title',
        ),
    ]
