# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0007_auto_20170629_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
