# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0008_userfile_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='filetype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
