# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharer', '0009_userfile_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='filetype',
        ),
        migrations.AddField(
            model_name='userfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
